<a href="https://colab.research.google.com/github/Flychuban/Decision-Tree-Exercise/blob/main/DecisionTreeRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('/content/drive/MyDrive/DecisionTreeExercise/airfoil_noise_data.csv')
data.head(10)

     x0   x1      x2    x3        x4        y
0   800  0.0  0.3048  71.3  0.002663  126.201
1  1000  0.0  0.3048  71.3  0.002663  125.201
2  1250  0.0  0.3048  71.3  0.002663  125.951
3  1600  0.0  0.3048  71.3  0.002663  127.591
4  2000  0.0  0.3048  71.3  0.002663  127.461
5  2500  0.0  0.3048  71.3  0.002663  125.571
6  3150  0.0  0.3048  71.3  0.002663  125.201
7  4000  0.0  0.3048  71.3  0.002663  123.061
8  5000  0.0  0.3048  71.3  0.002663  121.301
9  6300  0.0  0.3048  71.3  0.002663  119.541

In [4]:
class Node():
  def __init__(self, feature_index=None, threshold=None, left=None, right=None, var_red=None, value=None):
    self.feature_index = feature_index
    self.threshold = threshold
    self.left = left
    self.right = right
    self.var_red = var_red
    self.value = value

In [5]:
class DecisionTreeRegressor():
  def __init__(self, min_samples_split=2, max_depth=2):
    self.root = None
    self.min_samples_split = min_samples_split
    self.max_depth = max_depth

  def build_tree(self, dataset, curr_depth=0):
    X, Y = dataset[:, :-1], dataset[:, -1]
    num_samples, num_features = np.shape(X)
    best_split = {}
    if num_samples >= self.min_samples_split and curr_depth <= self.max_depth:
      best_split = self.get_best_split(dataset, num_samples, num_features)
      if best_split['var_red'] > 0:
        left_subtree = self.build_tree(best_split['dataset_left'], curr_depth+1)
        right_subtree = self.build_tree(best_split['dataset_right'], curr_depth+1)

        return Node(best_split['feature_index'], best_split['threshold'], left_subtree, right_subtree, best_split['var_red'])

    leaf_value = self.calculate_leaf_value(Y)
    return Node(value = leaf_value)